auth_tokens:
  ngrok: authtoken_ngrok
  spoonacular: apikey_spoonacular

external_urls:
  inference: URL
  local_recipe: URL
  ngrok_url: URL

get_nutrition_from_generated_recipe_title: True
is_production: False