[postgres]
host = "localhost"
port = "5432"
database = "postgres"
user = "postgres"
password = "password_placeholder"

[theme]
primaryColor="#aaa7a7"
backgroundColor="#000000"
secondaryBackgroundColor="#000000"
textColor="#ffffff"



